/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpetrator_manangement_system;

import javax.swing.JFrame;

/**
 *
 * @author Shehan
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        //Full Screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_content = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        input_content = new javax.swing.JPanel();
        full_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name_initials = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        nick_names = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        male_rad_btn = new javax.swing.JRadioButton();
        female_rad_btn = new javax.swing.JRadioButton();
        dob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        status_combo_box = new javax.swing.JComboBox<>();
        spouse = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        birth_place = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        children = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        parents = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        image_preview = new javax.swing.JLabel();
        insert_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        submit_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Register Perpetrator");
        setResizable(false);

        title_content.setBackground(new java.awt.Color(0, 11, 40));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(202, 225, 252));
        jLabel1.setText("National Perpetrator Database");
        jLabel1.setAutoscrolls(true);
        jLabel1.setMinimumSize(new java.awt.Dimension(172, 20));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(202, 225, 252));
        jLabel2.setText("Register");
        jLabel2.setAutoscrolls(true);
        jLabel2.setMinimumSize(new java.awt.Dimension(172, 20));

        javax.swing.GroupLayout title_contentLayout = new javax.swing.GroupLayout(title_content);
        title_content.setLayout(title_contentLayout);
        title_contentLayout.setHorizontalGroup(
            title_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_contentLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(title_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        title_contentLayout.setVerticalGroup(
            title_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_contentLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        input_content.setBackground(new java.awt.Color(0, 11, 40));

        full_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        full_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                full_nameMouseClicked(evt);
            }
        });
        full_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                full_nameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(202, 225, 252));
        jLabel3.setText("Fulll Name");

        name_initials.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name_initials.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                name_initialsMouseClicked(evt);
            }
        });
        name_initials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_initialsActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(202, 225, 252));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(202, 225, 252));
        jLabel5.setText("Name with Initials");

        id1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        id1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                id1MouseClicked(evt);
            }
        });
        id1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id1ActionPerformed(evt);
            }
        });

        nick_names.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nick_names.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nick_namesMouseClicked(evt);
            }
        });
        nick_names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nick_namesActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(202, 225, 252));
        jLabel6.setText("Nick Names");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(202, 225, 252));
        jLabel7.setText("Gender");

        male_rad_btn.setForeground(new java.awt.Color(202, 225, 252));
        male_rad_btn.setText("Male");

        female_rad_btn.setForeground(new java.awt.Color(202, 225, 252));
        female_rad_btn.setText("Female");

        dob.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dobMouseClicked(evt);
            }
        });
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(202, 225, 252));
        jLabel8.setText("Date of Birth");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(202, 225, 252));
        jLabel9.setText("Status");

        status_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Married", "Unmarried" }));
        status_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                status_combo_boxActionPerformed(evt);
            }
        });

        spouse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spouseMouseClicked(evt);
            }
        });
        spouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(202, 225, 252));
        jLabel10.setText("Spouse");

        birth_place.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        birth_place.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birth_placeMouseClicked(evt);
            }
        });
        birth_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birth_placeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(202, 225, 252));
        jLabel11.setText("Place");

        children.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        children.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                childrenMouseClicked(evt);
            }
        });
        children.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                childrenActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(202, 225, 252));
        jLabel12.setText("Children");

        parents.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        parents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parentsMouseClicked(evt);
            }
        });
        parents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentsActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(202, 225, 252));
        jLabel13.setText("Parents");

        image_preview.setForeground(new java.awt.Color(242, 242, 242));
        image_preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_preview.setText("image preview");
        image_preview.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(202, 225, 252), 2, true));

        insert_btn.setText("Insert Image");
        insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insert_btnActionPerformed(evt);
            }
        });

        description.setColumns(20);
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(202, 225, 252));
        jLabel16.setText("Description");

        submit_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submit_btn.setText("Submit Form");

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout input_contentLayout = new javax.swing.GroupLayout(input_content);
        input_content.setLayout(input_contentLayout);
        input_contentLayout.setHorizontalGroup(
            input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(input_contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(input_contentLayout.createSequentialGroup()
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(input_contentLayout.createSequentialGroup()
                                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_contentLayout.createSequentialGroup()
                                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10))
                                        .addGap(14, 14, 14))
                                    .addGroup(input_contentLayout.createSequentialGroup()
                                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)))
                                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nick_names, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(full_name, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_initials, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, input_contentLayout.createSequentialGroup()
                                        .addComponent(male_rad_btn)
                                        .addGap(18, 18, 18)
                                        .addComponent(female_rad_btn)
                                        .addGap(0, 305, Short.MAX_VALUE))
                                    .addComponent(dob, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(birth_place, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(input_contentLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(children, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spouse)
                                    .addComponent(parents))))
                        .addGap(137, 137, 137)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(image_preview, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(input_contentLayout.createSequentialGroup()
                                .addComponent(submit_btn)
                                .addGap(18, 18, 18)
                                .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_contentLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(status_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insert_btn)))
                .addGap(23, 23, 23))
        );
        input_contentLayout.setVerticalGroup(
            input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, input_contentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(input_contentLayout.createSequentialGroup()
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(id1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_initials, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nick_names, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(male_rad_btn)
                            .addComponent(female_rad_btn)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(birth_place, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(image_preview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(input_contentLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(input_contentLayout.createSequentialGroup()
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(status_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insert_btn))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spouse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(children, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(input_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(parents, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(90, 90, 90))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void full_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_full_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_full_nameActionPerformed

    private void full_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_full_nameMouseClicked
        
    }//GEN-LAST:event_full_nameMouseClicked

    private void name_initialsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_name_initialsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_name_initialsMouseClicked

    private void name_initialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_initialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_initialsActionPerformed

    private void id1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_id1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_id1MouseClicked

    private void id1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id1ActionPerformed

    private void nick_namesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nick_namesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nick_namesMouseClicked

    private void nick_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nick_namesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nick_namesActionPerformed

    private void dobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dobMouseClicked

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobActionPerformed

    private void status_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_status_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_status_combo_boxActionPerformed

    private void spouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spouseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseMouseClicked

    private void spouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseActionPerformed

    private void birth_placeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birth_placeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_placeMouseClicked

    private void birth_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birth_placeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birth_placeActionPerformed

    private void childrenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_childrenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenMouseClicked

    private void childrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_childrenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_childrenActionPerformed

    private void parentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_parentsMouseClicked

    private void parentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentsActionPerformed

    private void insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insert_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insert_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField birth_place;
    private javax.swing.JTextField children;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField dob;
    private javax.swing.JRadioButton female_rad_btn;
    private javax.swing.JTextField full_name;
    private javax.swing.JTextField id1;
    private javax.swing.JLabel image_preview;
    private javax.swing.JPanel input_content;
    private javax.swing.JButton insert_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male_rad_btn;
    private javax.swing.JTextField name_initials;
    private javax.swing.JTextField nick_names;
    private javax.swing.JTextField parents;
    private javax.swing.JTextField spouse;
    private javax.swing.JComboBox<String> status_combo_box;
    private javax.swing.JButton submit_btn;
    private javax.swing.JPanel title_content;
    // End of variables declaration//GEN-END:variables
}
